### ISSUE TITLE
Some URL paths already exists in url_rewrite table and not related

### ISSUE THREAD

**Issue by mesnitu** [olegkoval/magento2-regenerate_url_rewrites#101]
Hi
Maybe not a issue, I get a lot of this info. How do I get around this stuff? 
I've already tested and deleted all records on url_rewrite table.... where is this coming from ? 
Or do I really have to delete in the admin one by one?
Thanks

> [CONSOLE MESSAGES]
> Some URL paths already exists in url_rewrite table and not related to Product ID: 4402. Please remove them and execute this command ag
> ain. You can find them by following SQL:
> SELECT * FROM url_rewrite WHERE store_id=1 AND request_path IN (...

**Comment by saxsax1995** [comment]
I've the same issue with version 1.4.3, do you have any solution for this yet?

**Comment by olegkoval** [comment]
Hello @mesnitu , @saxsax1995 

This happens when you have two products with same name - so, url_key and Url Rewrites for this products are the same.

Starting from version 1.5.0 this situation is resolved by adding a number suffix ("url-key-of-product-1") to the second Url Rewrite. For the first product Url Rewrite will be original ("url-key-of-product").

Please update extension.

Best regards,
Oleg Koval
