### ISSUE TITLE
URL key for specified store already exists.

### ISSUE THREAD

**Issue by koopjesboom** [olegkoval/magento2-regenerate_url_rewrites#11]
Best,

Struggling with this issue from magento version 2.0 now on version 2.2.3 and still the same issue when saving products and duplicate products. No solution worked for me.

I used your tool to repair this issue : URL key for specified store already exists.
But is is giving me the same message in SSH/putty during execution of your tool..

Do you have any suggestions?

Best regards Bram

**Comment by olegkoval** [comment]
Hi Bram.

The problem is not in Magento code or custom extensions code. Looks like you have a 2 (maybe more) products in the same store and/or in same category with same name (and URL key):

1) Magento get collection of products to re-build URL Rewrites
2) <loop>
3) based on product name Magento generate URL key (or use existed)
3.1) if current product have same name as some previous product then Magento generate same URL key based on product name
4) Magento try to save it in DB
4.1) DB return unique key error (can't save URL key for same store  because this URL key already exists)
4.2) if DB return this error then Magento show you "URL key exists" error message
5) next product
6) </loop>
7) Done

So, the solution for you: find products with same name and update the name (one of product) or set custom URL key for one of this product (for example add a "-1" at the end of URL key).

**Comment by koopjesboom** [comment]
@olegkoval Sorry for the late response, yes i understand this issue. I think a lot of people facing this issue. In stead of paying a expensive developer it would be nice some one creates a scanner which points out de duplicated contend. Mus be easy for a developer and he can ask a (small) amount of money. I Think developers are unaware how many small budget people are using magento. In my country 90€ an hour is cheap for a magento developer. We need solutions to make magento affordable for everyone. They bill 3 hours for this issue and they copy paste your solution. Welcome to the Netherlands here they keep up steeling from the unknown "laugh".

**Comment by olegkoval** [comment]
@koopjesboom Thank you for reply.
Yes, I know about "stealing" problem and this is not only in Netherlands. The whole world is "sick" by this.

`it would be nice some one creates a scanner which points out de duplicated contend`
I think I will take care this and will made a next free extension (command line feature or, maybe, as admin panel feature).

`Welcome to the Netherlands.`
I plan to visit Netherlands in next week. So, if you want - we can a meet ;)

**Comment by koopjesboom** [comment]
@olegkoval  Where in the Netherlands do you stay? Maybe you can visit my company. I can show you how I do things myself without programming education.

**Comment by olegkoval** [comment]
@koopjesboom In the Eindhoven. You can use email or WatsApp to contact with me.

**Comment by koopjesboom** [comment]
Oke, I am in Groot-Ammers nearby Rotterdam. If you want or are able to visit our company let me know.

**Comment by olegkoval** [comment]
@koopjesboom Maybe in the friday, afternoon?

**Comment by koopjesboom** [comment]
Yes, I send you an e-mail.

**Comment by koopjesboom** [comment]
@olegkoval Did you manage to create a tool or extension to show duplicated contend?

Best regards Bram
