### ISSUE TITLE
URL key for specified store already exists.

### ISSUE THREAD

**Issue by agavshinde** [olegkoval/magento2-regenerate_url_rewrites#14]
Hello,

Thanks to provide such a useful extension. I have used it one of the magento sites It works good but at another site I am getting the error 'URL key for specified store already exists.'  when run the url rewrite command. Please let me know possible solution to fix the problem.

Regards
Ashish

**Comment by olegkoval** [comment]
Hello.

Looks like you have a 2 (maybe more) products in the same store and/or in same category with same name (and URL key):

1) Magento get collection of products to re-build URL Rewrites
2) \<loop>
3) based on product name Magento generate URL key (or use existed)
3.1) if current product have same name as some previous product then Magento generate same URL key based on product name
4) Magento try to save it in DB
4.1) DB return unique key error (can't save URL key for same store because this URL key already exists)
4.2) if DB return this error then Magento show you "URL key exists" error message
5) next product
6) \</loop>
7) Done

So, the solution for you: find products with same name and update the name (one of product) or set custom URL key for one of this product (for example add a "-1" at the end of URL key).
