### ISSUE TITLE
URL KEY PRODUCT UNSET 

### ISSUE THREAD

**Issue by mattiamagma** [olegkoval/magento2-regenerate_url_rewrites#44]
The url key of product is unset in all store view when i run a command and another problem is that in a specific store store view (Es. en it fr) is impossible to set  flag 'Use Default Value'  of Url key.

This corrupts url of products.

**Comment by quyendam2612** [comment]
same issue. just spotted today.

**Comment by Userr017** [comment]
I have same issue. Please fix soon as possible!

**Comment by olegkoval** [comment]
Hello @mattiamagma , @quyendam2612 , @Userr017 

Please, upgrade extension to version [1.3.0](https://github.com/olegkoval/magento2-regenerate_url_rewrites/releases/tag/v1.3.0). I've added option "--no-clean-url-key".

If you will use this option then script will not clean an existed url keys when re-generate URL rewrites. BUT take into account:
when Magento generate URL rewrites for some product it check if product have a url_key value and use it (and do not take into account "name" value, even if you modified it), otherwise (if url_key not exists or have an empty value) Magento use a product name to generate new url_key and then use it to generate a URL rewrites.

So, if you will use this option then Magento will generate URL rewrites based on "url_key" value (instead of "name" attribute value).

Best regards,
Oleg Koval
