### ISSUE TITLE
Product Url Key 

### ISSUE THREAD

**Issue by aligokayduman** [olegkoval/magento2-regenerate_url_rewrites#49]
Hi Oleg. When i start regenerate process, your code deleted all of product's url keys from catalog_product_entity_varchar table. url key attribute_id=126

**Comment by Userr017** [comment]
I have same issue. Please fix soon as possible!

**Comment by olegkoval** [comment]
Hello @aligokayduman , @Userr017 , @mdesplenter 

Please, upgrade extension to version [1.3.0](https://github.com/olegkoval/magento2-regenerate_url_rewrites/releases/tag/v1.3.0). I've added option "--no-clean-url-key".

If you will use this option then script will not clean an existed url keys when re-generate URL rewrites. BUT take into account:
when Magento generate URL rewrites for some product it check if product have a url_key value and use it (and do not take into account "name" value, even if you modified it), otherwise (if url_key not exists or have an empty value) Magento use a product name to generate new url_key and then use it to generate a URL rewrites.

So, if you will use this option then Magento will generate URL rewrites based on "url_key" value (instead of "name" attribute value).

**Comment by Userr017** [comment]
Still same issue. I have two stores and all product url keys is lost after command bin/magento ok:urlrewrites:regenerate.

Tested also commands and doesn't work:  bin/magento ok:urlrewrites:regenerate --no-clean-url-key and bin/magento ok:urlrewrites:regenerate --save-old-urls

![empty](https://user-images.githubusercontent.com/26794034/47749973-f0ebf200-dc96-11e8-8618-b754fb016c8b.JPG)
